// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoviesBE.Migrations
{
    [DbContext(typeof(MoviesBEDbContext))]
    [Migration("20240423232227_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("MoviesId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("GenreMovie");
                });

            modelBuilder.Entity("MoviesBE.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Western"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fantasy"
                        });
                });

            modelBuilder.Entity("MoviesBE.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateReleased")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateReleased = new DateTime(2013, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bright, fragrant, and sweet",
                            Image = "https://m.media-amazon.com/images/I/514z-fxF0uL._SX300_SY300_QL70_FMwebp_.jpg",
                            Title = "Thor: The Dark World"
                        },
                        new
                        {
                            Id = 2,
                            DateReleased = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A thief who enters the dreams of others to steal secrets from their subconscious.",
                            Image = "https://m.media-amazon.com/images/I/91l3cX6a4ZL._SL1500_.jpg",
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 3,
                            DateReleased = new DateTime(2010, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A story about the founders of the social-networking website, Facebook.",
                            Image = "https://m.media-amazon.com/images/I/51DnOUsPegL._AC_SY679_.jpg",
                            Title = "The Social Network"
                        },
                        new
                        {
                            Id = 4,
                            DateReleased = new DateTime(2012, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Earth's mightiest heroes must come together and learn to fight as a team.",
                            Image = "https://m.media-amazon.com/images/I/81vTHovrz+L._AC_SY679_.jpg",
                            Title = "The Avengers"
                        },
                        new
                        {
                            Id = 5,
                            DateReleased = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Image = "https://m.media-amazon.com/images/I/91jlm3rVKOL._AC_SY679_.jpg",
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 6,
                            DateReleased = new DateTime(2015, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A woman rebels against a tyrannical ruler in postapocalyptic Australia.",
                            Image = "https://m.media-amazon.com/images/I/61A8Ezv0YRL._AC_SY679_.jpg",
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            Id = 7,
                            DateReleased = new DateTime(2018, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
                            Image = "https://m.media-amazon.com/images/I/91Nz5QZvb0L._AC_SY679_.jpg",
                            Title = "Black Panther"
                        },
                        new
                        {
                            Id = 8,
                            DateReleased = new DateTime(2019, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
                            Image = "https://m.media-amazon.com/images/I/81MCeOFWFJL._AC_SY679_.jpg",
                            Title = "Parasite"
                        },
                        new
                        {
                            Id = 9,
                            DateReleased = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
                            Image = "https://m.media-amazon.com/images/I/71hXrd1cmRL._AC_SY679_.jpg",
                            Title = "Joker"
                        },
                        new
                        {
                            Id = 10,
                            DateReleased = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
                            Image = "https://m.media-amazon.com/images/I/81ai9zxNP1L._AC_SY679_.jpg",
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 11,
                            DateReleased = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            Image = "https://m.media-amazon.com/images/I/81rXmI0jeyL._AC_SY679_.jpg",
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 12,
                            DateReleased = new DateTime(2009, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
                            Image = "https://m.media-amazon.com/images/I/71ZMrPH9ZGL._AC_SY679_.jpg",
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = 13,
                            DateReleased = new DateTime(2010, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it's up to Woody to convince the other toys that they weren't abandoned and to return home.",
                            Image = "https://m.media-amazon.com/images/I/81OBK2NcFgL._AC_SY679_.jpg",
                            Title = "Toy Story 3"
                        },
                        new
                        {
                            Id = 14,
                            DateReleased = new DateTime(2011, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.",
                            Image = "https://m.media-amazon.com/images/I/81RKysa9WKL._AC_SY679_.jpg",
                            Title = "Harry Potter and the Deathly Hallows: Part 2"
                        },
                        new
                        {
                            Id = 15,
                            DateReleased = new DateTime(2012, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Katniss Everdeen voluntarily takes her younger sister's place in the Hunger Games, a televised competition in which two teenagers from each of the twelve Districts of Panem are chosen at random to fight to the death.",
                            Image = "https://m.media-amazon.com/images/I/81e2SCdrPpL._AC_SY679_.jpg",
                            Title = "The Hunger Games"
                        },
                        new
                        {
                            Id = 16,
                            DateReleased = new DateTime(2013, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.",
                            Image = "https://m.media-amazon.com/images/I/91J8E6vOUwL._AC_SY679_.jpg",
                            Title = "Frozen"
                        },
                        new
                        {
                            Id = 17,
                            DateReleased = new DateTime(2014, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
                            Image = "https://m.media-amazon.com/images/I/81WXT06J7gL._AC_SY679_.jpg",
                            Title = "Guardians of the Galaxy"
                        },
                        new
                        {
                            Id = 18,
                            DateReleased = new DateTime(2015, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive.",
                            Image = "https://m.media-amazon.com/images/I/71jSJ1hM1XL._AC_SY679_.jpg",
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 19,
                            DateReleased = new DateTime(2016, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
                            Image = "https://m.media-amazon.com/images/I/71r6Pw6OBFLL._AC_SY679_.jpg",
                            Title = "La La Land"
                        },
                        new
                        {
                            Id = 20,
                            DateReleased = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
                            Image = "https://m.media-amazon.com/images/I/81E6rLEqRgL._AC_SY679_.jpg",
                            Title = "Get Out"
                        },
                        new
                        {
                            Id = 21,
                            DateReleased = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
                            Image = "https://m.media-amazon.com/images/I/71rWhfYP7-L._AC_SY679_.jpg",
                            Title = "Spider-Man: Into the Spider-Verse"
                        },
                        new
                        {
                            Id = 22,
                            DateReleased = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Two young British soldiers during the First World War are given an impossible mission: deliver a message deep in enemy territory that will stop 1,600 men, and one of the soldiers' brothers, from walking straight into a deadly trap.",
                            Image = "https://m.media-amazon.com/images/I/81bzWVm-M-L._AC_SY679_.jpg",
                            Title = "1917"
                        },
                        new
                        {
                            Id = 23,
                            DateReleased = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
                            Image = "https://m.media-amazon.com/images/I/71bS40TWqgL._AC_SY679_.jpg",
                            Title = "Tenet"
                        },
                        new
                        {
                            Id = 24,
                            DateReleased = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A musician who has lost his passion for music is transported out of his body and must find his way back with the help of an infant soul learning about herself.",
                            Image = "https://m.media-amazon.com/images/I/71cZKuCFpEL._AC_SY679_.jpg",
                            Title = "Soul"
                        });
                });

            modelBuilder.Entity("MoviesBE.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentReview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentReview = "Excellent movie, highly recommended.",
                            DateCreated = new DateTime(2024, 4, 23, 18, 22, 27, 554, DateTimeKind.Local).AddTicks(4047),
                            MovieId = 1,
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommentReview = "Enjoyed it, but pacing was a bit slow.",
                            DateCreated = new DateTime(2024, 4, 23, 18, 22, 27, 554, DateTimeKind.Local).AddTicks(4125),
                            MovieId = 2,
                            Rating = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentReview = "Decent movie, but expected more from the storyline.",
                            DateCreated = new DateTime(2024, 4, 23, 18, 22, 27, 554, DateTimeKind.Local).AddTicks(4129),
                            MovieId = 3,
                            Rating = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CommentReview = "Absolutely loved it, couldn't stop thinking about it!",
                            DateCreated = new DateTime(2024, 4, 23, 18, 22, 27, 554, DateTimeKind.Local).AddTicks(4132),
                            MovieId = 4,
                            Rating = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CommentReview = "Great action scenes, but the plot was a bit predictable.",
                            DateCreated = new DateTime(2024, 4, 23, 18, 22, 27, 554, DateTimeKind.Local).AddTicks(4136),
                            MovieId = 5,
                            Rating = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CommentReview = "Average movie, nothing too special.",
                            DateCreated = new DateTime(2024, 4, 23, 18, 22, 27, 554, DateTimeKind.Local).AddTicks(4139),
                            MovieId = 6,
                            Rating = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CommentReview = "One of the best movies I've seen in a long time!",
                            DateCreated = new DateTime(2024, 4, 23, 18, 22, 27, 554, DateTimeKind.Local).AddTicks(4142),
                            MovieId = 7,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            CommentReview = "Really enjoyed it, great performances from the cast.",
                            DateCreated = new DateTime(2024, 4, 23, 18, 22, 27, 554, DateTimeKind.Local).AddTicks(4145),
                            MovieId = 8,
                            Rating = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            CommentReview = "Hilarious movie, had me laughing from start to finish!",
                            DateCreated = new DateTime(2024, 4, 23, 18, 22, 27, 554, DateTimeKind.Local).AddTicks(4148),
                            MovieId = 9,
                            Rating = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CommentReview = "Some funny moments, but overall a bit too silly for my taste.",
                            DateCreated = new DateTime(2024, 4, 23, 18, 22, 27, 554, DateTimeKind.Local).AddTicks(4151),
                            MovieId = 10,
                            Rating = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MoviesBE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            Image = "https://example.com/images/alice.jpg",
                            IsAdmin = true,
                            Name = "Alex",
                            Uid = "123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            Image = "https://example.com/images/bob.jpg",
                            IsAdmin = true,
                            Name = "Fletcher",
                            Uid = "345"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@example.com",
                            Image = "https://example.com/images/charlie.jpg",
                            IsAdmin = true,
                            Name = "Charlie",
                            Uid = "345"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mary@example.com",
                            Image = "https://example.com/images/mary.jpg",
                            IsAdmin = true,
                            Name = "Mary",
                            Uid = "567"
                        });
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("MoviesBE.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesBE.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
