// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoviesBE.Migrations
{
    [DbContext(typeof(MoviesBEDbContext))]
    [Migration("20240427170735_EbachCreate2")]
    partial class EbachCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("MoviesId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("GenreMovie");
                });

            modelBuilder.Entity("MoviesBE.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Western"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fantasy"
                        });
                });

            modelBuilder.Entity("MoviesBE.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateReleased")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateReleased = new DateTime(2013, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bright, fragrant, and sweet",
                            Image = "https://m.media-amazon.com/images/I/514z-fxF0uL._SX300_SY300_QL70_FMwebp_.jpg",
                            Title = "Thor: The Dark World"
                        },
                        new
                        {
                            Id = 2,
                            DateReleased = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A thief who enters the dreams of others to steal secrets from their subconscious.",
                            Image = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg",
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 3,
                            DateReleased = new DateTime(2010, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A story about the founders of the social-networking website, Facebook.",
                            Image = "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8078163_p_v8_ad.jpg",
                            Title = "The Social Network"
                        },
                        new
                        {
                            Id = 4,
                            DateReleased = new DateTime(2012, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Earth's mightiest heroes must come together and learn to fight as a team.",
                            Image = "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
                            Title = "The Avengers"
                        },
                        new
                        {
                            Id = 5,
                            DateReleased = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Image = "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 6,
                            DateReleased = new DateTime(2015, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A woman rebels against a tyrannical ruler in postapocalyptic Australia.",
                            Image = "https://i.redd.it/mad-max-fury-road-2015-this-live-action-film-by-george-v0-h5q7wvt2yw2b1.jpg?width=793&format=pjpg&auto=webp&s=555a1a328f8cbbaea8fc814aa0be022c8af0da7b",
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            Id = 7,
                            DateReleased = new DateTime(2018, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
                            Image = "https://lumiere-a.akamaihd.net/v1/images/p_blackpanther_19754_4ac13f07.jpeg?region=0%2C0%2C540%2C810",
                            Title = "Black Panther"
                        },
                        new
                        {
                            Id = 8,
                            DateReleased = new DateTime(2019, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
                            Image = "https://miro.medium.com/v2/resize:fit:1400/1*QJYVaaRVrOF_0tlksmCYIQ.jpeg",
                            Title = "Parasite"
                        },
                        new
                        {
                            Id = 9,
                            DateReleased = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
                            Image = "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
                            Title = "Joker"
                        },
                        new
                        {
                            Id = 10,
                            DateReleased = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
                            Image = "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_.jpg",
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 11,
                            DateReleased = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            Image = "https://images.moviesanywhere.com/bd47f9b7d090170d79b3085804075d41/c6140695-a35f-46e2-adb7-45ed829fc0c0.jpg",
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 12,
                            DateReleased = new DateTime(2009, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
                            Image = "https://m.media-amazon.com/images/I/91N1lG+LBIS._AC_UF1000,1000_QL80_.jpg",
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = 13,
                            DateReleased = new DateTime(2010, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it's up to Woody to convince the other toys that they weren't abandoned and to return home.",
                            Image = "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_.jpg",
                            Title = "Toy Story 3"
                        },
                        new
                        {
                            Id = 14,
                            DateReleased = new DateTime(2011, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.",
                            Image = "https://images.moviesanywhere.com/5f0537520f90b687fc5db7f241affc4c/842c4e03-abee-4260-a170-bff52e63519a.jpg",
                            Title = "Harry Potter and the Deathly Hallows: Part 2"
                        },
                        new
                        {
                            Id = 15,
                            DateReleased = new DateTime(2012, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Katniss Everdeen voluntarily takes her younger sister's place in the Hunger Games, a televised competition in which two teenagers from each of the twelve Districts of Panem are chosen at random to fight to the death.",
                            Image = "https://m.media-amazon.com/images/M/MV5BMjA4NDg3NzYxMF5BMl5BanBnXkFtZTcwNTgyNzkyNw@@._V1_.jpg",
                            Title = "The Hunger Games"
                        },
                        new
                        {
                            Id = 16,
                            DateReleased = new DateTime(2013, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.",
                            Image = "https://lumiere-a.akamaihd.net/v1/images/p_frozen_18373_3131259c.jpeg",
                            Title = "Frozen"
                        },
                        new
                        {
                            Id = 17,
                            DateReleased = new DateTime(2014, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/3/33/Guardians_of_the_Galaxy_%28film%29_poster.jpg",
                            Title = "Guardians of the Galaxy"
                        },
                        new
                        {
                            Id = 18,
                            DateReleased = new DateTime(2015, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive.",
                            Image = "https://m.media-amazon.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_.jpg",
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 19,
                            DateReleased = new DateTime(2016, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
                            Image = "https://static.wikia.nocookie.net/filmguide/images/2/28/La_La_Land.png/revision/latest?cb=20220422085615",
                            Title = "La La Land"
                        },
                        new
                        {
                            Id = 20,
                            DateReleased = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/a/a3/Get_Out_poster.png",
                            Title = "Get Out"
                        },
                        new
                        {
                            Id = 21,
                            DateReleased = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
                            Image = "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_.jpg",
                            Title = "Spider-Man: Into the Spider-Verse"
                        },
                        new
                        {
                            Id = 22,
                            DateReleased = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Two young British soldiers during the First World War are given an impossible mission: deliver a message deep in enemy territory that will stop 1,600 men, and one of the soldiers' brothers, from walking straight into a deadly trap.",
                            Image = "https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_.jpg",
                            Title = "1917"
                        },
                        new
                        {
                            Id = 23,
                            DateReleased = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
                            Image = "https://m.media-amazon.com/images/M/MV5BMzU3YWYwNTQtZTdiMC00NjY5LTlmMTMtZDFlYTEyODBjMTk5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
                            Title = "Tenet"
                        },
                        new
                        {
                            Id = 24,
                            DateReleased = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A musician who has lost his passion for music is transported out of his body and must find his way back with the help of an infant soul learning about herself.",
                            Image = "https://m.media-amazon.com/images/M/MV5BZGE1MDg5M2MtNTkyZS00MTY5LTg1YzUtZTlhZmM1Y2EwNmFmXkEyXkFqcGdeQXVyNjA3OTI0MDc@._V1_.jpg",
                            Title = "Soul"
                        },
                        new
                        {
                            Id = 25,
                            DateReleased = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Image = "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 26,
                            DateReleased = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
                            Image = "https://m.media-amazon.com/images/I/410KAWNjZiL._AC_UF1000,1000_QL80_.jpg",
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 27,
                            DateReleased = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Image = "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 28,
                            DateReleased = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
                            Image = "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 29,
                            DateReleased = new DateTime(2003, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Blacksmith Will Turner teams up with eccentric pirate Captain Jack Sparrow to save his love, the governor's daughter, from Jack's former pirate allies who are now undead.",
                            Image = "https://m.media-amazon.com/images/M/MV5BNGYyZGM5MGMtYTY2Ni00M2Y1LWIzNjQtYWUzM2VlNGVhMDNhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
                            Title = "Pirates of the Caribbean: The Curse of the Black Pearl"
                        },
                        new
                        {
                            Id = 30,
                            DateReleased = new DateTime(2003, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            Image = "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            Id = 31,
                            DateReleased = new DateTime(2004, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.",
                            Image = "https://m.media-amazon.com/images/M/MV5BMTY5OTU0OTc2NV5BMl5BanBnXkFtZTcwMzU4MDcyMQ@@._V1_.jpg",
                            Title = "The Incredibles"
                        },
                        new
                        {
                            Id = 32,
                            DateReleased = new DateTime(2006, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
                            Image = "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p162564_p_v8_ag.jpg",
                            Title = "The Departed"
                        },
                        new
                        {
                            Id = 33,
                            DateReleased = new DateTime(2007, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/8/8b/No_Country_for_Old_Men_poster.jpg",
                            Title = "No Country for Old Men"
                        },
                        new
                        {
                            Id = 34,
                            DateReleased = new DateTime(2009, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Seventy-eight year old Carl Fredricksen travels to Paradise Falls in his home equipped with balloons, inadvertently taking a young stowaway.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/0/05/Up_%282009_film%29.jpg",
                            Title = "Up"
                        },
                        new
                        {
                            Id = 35,
                            DateReleased = new DateTime(2013, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Two astronauts work together to survive after an accident leaves them stranded in space.",
                            Image = "https://m.media-amazon.com/images/M/MV5BNjE5MzYwMzYxMF5BMl5BanBnXkFtZTcwOTk4MTk0OQ@@._V1_.jpg",
                            Title = "Gravity"
                        },
                        new
                        {
                            Id = 36,
                            DateReleased = new DateTime(2014, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A promising young drummer enrolls at a cutthroat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
                            Image = "https://i.ebayimg.com/images/g/pLYAAOSw3v5Yt~VZ/s-l1600.jpg",
                            Title = "Whiplash"
                        },
                        new
                        {
                            Id = 37,
                            DateReleased = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.",
                            Image = "https://m.media-amazon.com/images/M/MV5BMDE5OWMzM2QtOTU2ZS00NzAyLWI2MDEtOTRlYjIxZGM0OWRjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg",
                            Title = "The Revenant"
                        },
                        new
                        {
                            Id = 38,
                            DateReleased = new DateTime(2019, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A detective investigates the death of a patriarch of an eccentric, combative family.",
                            Image = "https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_.jpg",
                            Title = "Knives Out"
                        },
                        new
                        {
                            Id = 39,
                            DateReleased = new DateTime(2017, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who's been missing for thirty years.",
                            Image = "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_.jpg",
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            Id = 40,
                            DateReleased = new DateTime(2019, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A mob hitman recalls his possible involvement with the slaying of Jimmy Hoffa.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/8/80/The_Irishman_poster.jpg",
                            Title = "The Irishman"
                        });
                });

            modelBuilder.Entity("MoviesBE.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentReview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentReview = "Excellent movie, highly recommended.",
                            DateCreated = new DateTime(2024, 4, 27, 12, 7, 34, 647, DateTimeKind.Local).AddTicks(5870),
                            MovieId = 1,
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommentReview = "Enjoyed it, but pacing was a bit slow.",
                            DateCreated = new DateTime(2024, 4, 27, 12, 7, 34, 647, DateTimeKind.Local).AddTicks(5920),
                            MovieId = 2,
                            Rating = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentReview = "Decent movie, but expected more from the storyline.",
                            DateCreated = new DateTime(2024, 4, 27, 12, 7, 34, 647, DateTimeKind.Local).AddTicks(5970),
                            MovieId = 3,
                            Rating = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CommentReview = "Absolutely loved it, couldn't stop thinking about it!",
                            DateCreated = new DateTime(2024, 4, 27, 12, 7, 34, 647, DateTimeKind.Local).AddTicks(5980),
                            MovieId = 4,
                            Rating = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CommentReview = "Great action scenes, but the plot was a bit predictable.",
                            DateCreated = new DateTime(2024, 4, 27, 12, 7, 34, 647, DateTimeKind.Local).AddTicks(5980),
                            MovieId = 5,
                            Rating = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CommentReview = "Average movie, nothing too special.",
                            DateCreated = new DateTime(2024, 4, 27, 12, 7, 34, 647, DateTimeKind.Local).AddTicks(5980),
                            MovieId = 6,
                            Rating = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CommentReview = "One of the best movies I've seen in a long time!",
                            DateCreated = new DateTime(2024, 4, 27, 12, 7, 34, 647, DateTimeKind.Local).AddTicks(5990),
                            MovieId = 7,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            CommentReview = "Really enjoyed it, great performances from the cast.",
                            DateCreated = new DateTime(2024, 4, 27, 12, 7, 34, 647, DateTimeKind.Local).AddTicks(5990),
                            MovieId = 8,
                            Rating = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            CommentReview = "Hilarious movie, had me laughing from start to finish!",
                            DateCreated = new DateTime(2024, 4, 27, 12, 7, 34, 647, DateTimeKind.Local).AddTicks(5990),
                            MovieId = 9,
                            Rating = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CommentReview = "Some funny moments, but overall a bit too silly for my taste.",
                            DateCreated = new DateTime(2024, 4, 27, 12, 7, 34, 647, DateTimeKind.Local).AddTicks(5990),
                            MovieId = 10,
                            Rating = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MoviesBE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Cillian_Murphy-2014.jpg/800px-Cillian_Murphy-2014.jpg",
                            IsAdmin = true,
                            Name = "Alex",
                            Uid = "123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            Image = "https://media.gq-magazine.co.uk/photos/5d13ad12976fa30cf6f3b2a2/1:1/w_1280,h_1280,c_limit/HP.jpg",
                            IsAdmin = true,
                            Name = "Fletcher",
                            Uid = "345"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@example.com",
                            Image = "https://s2.r29static.com/bin/entry/c71/0,0,2000,2400/720x864,85/1909057/image.webp",
                            IsAdmin = true,
                            Name = "Charlie",
                            Uid = "345"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mary@example.com",
                            Image = "https://s.hdnux.com/photos/01/17/67/35/20936552/6/1200x0.jpg",
                            IsAdmin = true,
                            Name = "Mary",
                            Uid = "567"
                        });
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("MoviesBE.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesBE.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoviesBE.Models.Review", b =>
                {
                    b.HasOne("MoviesBE.Models.Movie", null)
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoviesBE.Models.Movie", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
